plugins:
  - rubocop-minitest

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - vendor/**/*
    - tmp/**/*
    - examples/**/*

Style/Documentation:
  Enabled: false

Naming/MethodName:
  AllowedPatterns:
    - \A[A-Z][A-Za-z0-9_]*\z

Style/ArgumentsForwarding:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

Metrics/AbcSize:
  Max: 20
  Exclude:
    - test/**/*

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - test/**/*
    - "*.gemspec"

Metrics/ClassLength:
  Exclude:
    - test/**/*

Minitest/MultipleAssertions:
  Exclude:
    - test/**/*
